---

- name: grafana | install grafana gpg key
  become: true
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: grafana | add apt repository
  become: true
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    
- name: grafana | install grafana
  become: true
  apt:
    name: grafana
    state: present
    update_cache: true

- name: grafana | start and enable grafana service
  become: true
  systemd:
    name: grafana-server
    state: started
    enabled: true
        
      
